import os
import pygame
from pygame.locals import *
import sys

i = 0
pygame.init()
ventana = pygame.display.set_mode((500, 500))
color = (255, 255, 255)

while i == 0:
    for a in range(0, 500, 50):
        for b in range(0, 500, 50):
            pygame.draw.rect(ventana, color, pygame.Rect(a, b, 50, 50), 2)
            pygame.display.flip()
    break


def cargarimagenes():
    img = []
    img.append(pygame.image.load("1rojo.png"))
    img.append(pygame.image.load("2rojo.png"))
    img.append(pygame.image.load("3rojo.png"))
    img.append(pygame.image.load("4rojo.png"))
    img.append(pygame.image.load("5rojo.png"))
    img.append(pygame.image.load("6rojo.png"))
    img.append(pygame.image.load("7rojo.png"))
    img.append(pygame.image.load("8rojo.png"))
    img.append(pygame.image.load("9rojo.png"))
    img.append(pygame.image.load("srojo.png"))
    img.append(pygame.image.load("brojo.png"))
    img.append(pygame.image.load("frojo.png"))
    img.append(pygame.image.load("1azul.png"))
    img.append(pygame.image.load("2azul.png"))
    img.append(pygame.image.load("3azul.png"))
    img.append(pygame.image.load("4azul.png"))
    img.append(pygame.image.load("5azul.png"))
    img.append(pygame.image.load("6azul.png"))
    img.append(pygame.image.load("7azul.png"))
    img.append(pygame.image.load("8azul.png"))
    img.append(pygame.image.load("9azul.png"))
    img.append(pygame.image.load("sazul.png"))
    img.append(pygame.image.load("bazul.png"))
    img.append(pygame.image.load("fazul.png"))
    return img


imgs = cargarimagenes()

class ficha:
    estado = 1
    def __init__(self,ataque,equipo,numeroimagen,posicionx,posiciony):
        self.ataque=ataque
        self.equipo=equipo
        self.image = pygame.transform.scale(imgs[numeroimagen],[40,40])
        self.posicionx = posicionx
        self.posicionxy = posiciony


#1 rojo 2 azul 
unorojo= ficha(1,1,0,5,305)
dosrojo= ficha(2,1,1,55,305)
tresrojo1= ficha(3,1,2,105,305)
tresrojo2= ficha(3,1,2,155,305)
cuatrorojo1= ficha(4,1,3,205,305)
cuatrorojo2= ficha(4,1,3,255,305)
cuatrorojo3= ficha(4,1,3,305,305)
cincorojo1= ficha(5,1,4,355,305)
cincorojo2= ficha(5,1,4,405,305)
cincorojo3= ficha(5,1,4,455,305)
cincorojo4= ficha(5,1,4,5,355)
seisrojo1= ficha(6,1,5,55,355)
seisrojo2= ficha(6,1,5,105,355)
seisrojo3= ficha(6,1,5,155,355)
seisrojo4= ficha(6,1,5,205,355)
sieterojo1= ficha(7,1,6,255,355)
sieterojo2= ficha(7,1,6,305,355)
sieterojo3= ficha(7,1,6,355,355)
sieterojo4= ficha(7,1,6,405,355)
ochorojo1= ficha(8,1,7,455,355)
ochorojo2= ficha(8,1,7,5,405)
ochorojo3= ficha(8,1,7,55,405)
ochorojo4= ficha(8,1,7,105,405)
ochorojo5= ficha(8,1,7,155,405)
nueverojo1= ficha(9,1,8,205,405)
nueverojo2= ficha(9,1,8,255,405)
nueverojo3= ficha(9,1,8,305,405)
nueverojo4= ficha(9,1,8,355,405)
nueverojo5= ficha(9,1,8,405,405)
nueverojo6= ficha(9,1,8,455,405)
nueverojo7= ficha(9,1,8,5,455)
nueverojo8= ficha(9,1,8,55,455)
espiarojo= ficha(10,1,9,105,455)
bombarojo1= ficha(11,1,10,155,455)
bombarojo2= ficha(11,1,10,205,455)
bombarojo3= ficha(11,1,10,255,455)
bombarojo4= ficha(11,1,10,305,455)
bombarojo5= ficha(11,1,10,355,455)
bombarojo6= ficha(11,1,10,405,455)
banderarojo= ficha(12,1,11,455,455)
unoazul= ficha(1,2,12,5,5)
dosazul= ficha(2,2,13,55,5)
tresazul1= ficha(3,2,14,105,5)
tresazul2= ficha(3,2,14,155,5)
cuatroazul1= ficha(4,2,15,205,5)
cuatroazul2= ficha(4,2,15,255,5)
cuatroazul3= ficha(4,2,15,305,5)
cincoazul1= ficha(5,2,16,355,5)
cincoazul2= ficha(5,2,16,405,5)
cincoazul3= ficha(5,2,16,455,5)
cincoazul4= ficha(5,2,16,5,55)
seisazul1= ficha(6,2,17,55,55)
seisazul2= ficha(6,2,17,105,55)
seisazul3= ficha(6,2,17,155,55)
seisazul4= ficha(6,2,17,205,55)
sieteazul1= ficha(7,2,18,255,55)
sieteazul2= ficha(7,2,18,305,55)
sieteazul3= ficha(7,2,18,355,55)
sieteazul4= ficha(7,2,18,405,55)
ochoazul1= ficha(8,2,19,455,55)
ochoazul2= ficha(8,2,19,5,105)
ochoazul3= ficha(8,2,19,55,105)
ochoazul4= ficha(8,2,19,105,105)
ochoazul5= ficha(8,2,19,155,105)
nueveazul1= ficha(9,2,20,205,105)
nueveazul2= ficha(9,2,20,255,105)
nueveazul3= ficha(9,2,20,305,105)
nueveazul4= ficha(9,2,20,355,105)
nueveazul5= ficha(9,2,20,405,105)
nueveazul6= ficha(9,2,20,455,105)
nueveazul7= ficha(9,2,20,5,155)
nueveazul8= ficha(9,2,20,55,155)
espiaazul= ficha(10,2,21,105,155)
bombaazul1= ficha(11,2,22,155,155)
bombaazul2= ficha(11,2,22,205,155)
bombaazul3= ficha(11,2,22,255,155)
bombaazul4= ficha(11,2,22,305,155)
bombaazul5= ficha(11,2,22,355,155)
bombaazul6= ficha(11,2,22,405,155)
banderaazul= ficha(12,2,23,455,155)



game_over = False

while not game_over:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            game_over = True
            sys.exit()
    ventana.blit(unorojo.image, [unorojo.posicionx,unorojo.posicionxy])
    ventana.blit(dosrojo.image, [dosrojo.posicionx,dosrojo.posicionxy])
    ventana.blit(tresrojo1.image, [tresrojo1.posicionx,tresrojo1.posicionxy])
    ventana.blit(tresrojo2.image, [tresrojo2.posicionx,tresrojo2.posicionxy])
    ventana.blit(cuatrorojo1.image, [cuatrorojo1.posicionx,cuatrorojo1.posicionxy])
    ventana.blit(cuatrorojo2.image, [cuatrorojo2.posicionx,cuatrorojo2.posicionxy])
    ventana.blit(cuatrorojo3.image, [cuatrorojo3.posicionx,cuatrorojo3.posicionxy])
    ventana.blit(cincorojo1.image, [cincorojo1.posicionx,cincorojo1.posicionxy])
    ventana.blit(cincorojo2.image, [cincorojo2.posicionx,cincorojo2.posicionxy])
    ventana.blit(cincorojo3.image, [cincorojo3.posicionx,cincorojo3.posicionxy])
    ventana.blit(cincorojo4.image, [cincorojo4.posicionx,cincorojo4.posicionxy])
    ventana.blit(seisrojo1.image, [seisrojo1.posicionx,seisrojo1.posicionxy])
    ventana.blit(seisrojo2.image, [seisrojo2.posicionx,seisrojo2.posicionxy])
    ventana.blit(seisrojo3.image, [seisrojo3.posicionx,seisrojo3.posicionxy])
    ventana.blit(seisrojo4.image, [seisrojo4.posicionx,seisrojo4.posicionxy])
    ventana.blit(sieterojo1.image, [sieterojo1.posicionx,sieterojo1.posicionxy])
    ventana.blit(sieterojo2.image, [sieterojo2.posicionx,sieterojo2.posicionxy])
    ventana.blit(sieterojo3.image, [sieterojo3.posicionx,sieterojo3.posicionxy])
    ventana.blit(sieterojo4.image, [sieterojo4.posicionx,sieterojo4.posicionxy])
    ventana.blit(ochorojo1.image, [ochorojo1.posicionx,ochorojo1.posicionxy])
    ventana.blit(ochorojo2.image, [ochorojo2.posicionx,ochorojo2.posicionxy])
    ventana.blit(ochorojo3.image, [ochorojo3.posicionx,ochorojo3.posicionxy])
    ventana.blit(ochorojo4.image, [ochorojo4.posicionx,ochorojo4.posicionxy])
    ventana.blit(ochorojo5.image, [ochorojo5.posicionx,ochorojo5.posicionxy])
    ventana.blit(nueverojo1.image, [nueverojo1.posicionx,nueverojo1.posicionxy])
    ventana.blit(nueverojo2.image, [nueverojo2.posicionx,nueverojo2.posicionxy])
    ventana.blit(nueverojo3.image, [nueverojo3.posicionx,nueverojo3.posicionxy])
    ventana.blit(nueverojo4.image, [nueverojo4.posicionx,nueverojo4.posicionxy])
    ventana.blit(nueverojo5.image, [nueverojo5.posicionx,nueverojo5.posicionxy])
    ventana.blit(nueverojo6.image, [nueverojo6.posicionx,nueverojo6.posicionxy])
    ventana.blit(nueverojo7.image, [nueverojo7.posicionx,nueverojo7.posicionxy])
    ventana.blit(nueverojo8.image, [nueverojo8.posicionx,nueverojo8.posicionxy])
    ventana.blit(espiarojo.image, [espiarojo.posicionx,espiarojo.posicionxy])
    ventana.blit(bombarojo1.image, [bombarojo1.posicionx,bombarojo1.posicionxy])
    ventana.blit(bombarojo2.image, [bombarojo2.posicionx,bombarojo2.posicionxy])
    ventana.blit(bombarojo3.image, [bombarojo3.posicionx,bombarojo3.posicionxy])
    ventana.blit(bombarojo4.image, [bombarojo4.posicionx,bombarojo4.posicionxy])
    ventana.blit(bombarojo5.image, [bombarojo5.posicionx,bombarojo5.posicionxy])
    ventana.blit(bombarojo6.image, [bombarojo6.posicionx,bombarojo6.posicionxy])
    ventana.blit(banderarojo.image, [banderarojo.posicionx,banderarojo.posicionxy])
    ventana.blit(unoazul.image, [unoazul.posicionx,unoazul.posicionxy])
    ventana.blit(dosazul.image, [dosazul.posicionx,dosazul.posicionxy])
    ventana.blit(tresazul1.image, [tresazul1.posicionx,tresazul1.posicionxy])
    ventana.blit(tresazul2.image, [tresazul2.posicionx,tresazul2.posicionxy])
    ventana.blit(cuatroazul1.image, [cuatroazul1.posicionx,cuatroazul1.posicionxy])
    ventana.blit(cuatroazul2.image, [cuatroazul2.posicionx,cuatroazul2.posicionxy])
    ventana.blit(cuatroazul3.image, [cuatroazul3.posicionx,cuatroazul3.posicionxy])
    ventana.blit(cincoazul1.image, [cincoazul1.posicionx,cincoazul1.posicionxy])
    ventana.blit(cincoazul2.image, [cincoazul2.posicionx,cincoazul2.posicionxy])
    ventana.blit(cincoazul3.image, [cincoazul3.posicionx,cincoazul3.posicionxy])
    ventana.blit(cincoazul4.image, [cincoazul4.posicionx,cincoazul4.posicionxy])
    ventana.blit(seisazul1.image, [seisazul1.posicionx,seisazul1.posicionxy])
    ventana.blit(seisazul2.image, [seisazul2.posicionx,seisazul2.posicionxy])
    ventana.blit(seisazul3.image, [seisazul3.posicionx,seisazul3.posicionxy])
    ventana.blit(seisazul4.image, [seisazul4.posicionx,seisazul4.posicionxy])
    ventana.blit(sieteazul1.image, [sieteazul1.posicionx,sieteazul1.posicionxy])
    ventana.blit(sieteazul2.image, [sieteazul2.posicionx,sieteazul2.posicionxy])
    ventana.blit(sieteazul3.image, [sieteazul3.posicionx,sieteazul3.posicionxy])
    ventana.blit(sieteazul4.image, [sieteazul4.posicionx,sieteazul4.posicionxy])
    ventana.blit(ochoazul1.image, [ochoazul1.posicionx,ochoazul1.posicionxy])
    ventana.blit(ochoazul2.image, [ochoazul2.posicionx,ochoazul2.posicionxy])
    ventana.blit(ochoazul3.image, [ochoazul3.posicionx,ochoazul3.posicionxy])
    ventana.blit(ochoazul4.image, [ochoazul4.posicionx,ochoazul4.posicionxy])
    ventana.blit(ochoazul5.image, [ochoazul5.posicionx,ochoazul5.posicionxy])
    ventana.blit(nueveazul1.image, [nueveazul1.posicionx,nueveazul1.posicionxy])
    ventana.blit(nueveazul2.image, [nueveazul2.posicionx,nueveazul2.posicionxy])
    ventana.blit(nueveazul3.image, [nueveazul3.posicionx,nueveazul3.posicionxy])
    ventana.blit(nueveazul4.image, [nueveazul4.posicionx,nueveazul4.posicionxy])
    ventana.blit(nueveazul5.image, [nueveazul5.posicionx,nueveazul5.posicionxy])
    ventana.blit(nueveazul6.image, [nueveazul6.posicionx,nueveazul6.posicionxy])
    ventana.blit(nueveazul7.image, [nueveazul7.posicionx,nueveazul7.posicionxy])
    ventana.blit(nueveazul8.image, [nueveazul8.posicionx,nueveazul8.posicionxy])
    ventana.blit(espiaazul.image, [espiaazul.posicionx,espiaazul.posicionxy])
    ventana.blit(bombaazul1.image, [bombaazul1.posicionx,bombaazul1.posicionxy])
    ventana.blit(bombaazul2.image, [bombaazul2.posicionx,bombaazul2.posicionxy])
    ventana.blit(bombaazul3.image, [bombaazul3.posicionx,bombaazul3.posicionxy])
    ventana.blit(bombaazul4.image, [bombaazul4.posicionx,bombaazul4.posicionxy])
    ventana.blit(bombaazul5.image, [bombaazul5.posicionx,bombaazul5.posicionxy])
    ventana.blit(bombaazul6.image, [bombaazul6.posicionx,bombaazul6.posicionxy])
    ventana.blit(banderaazul.image, [banderaazul.posicionx,banderaazul.posicionxy])
    pygame.display.flip()
    pygame.display.update()
